### ISSUE TITLE
segmentation violation when using a custom ReadSeeker

### ISSUE THREAD

**Issue by yanc0** [klippa-app/go-pdfium#137]
Hi folks !

I'm struggling debugging my app loading a document using the `ReadSeeker` way. My document is stored on a webserver and I use Range request to only read the bytes that I want on the distant file. It works fine until I try to render a page in pixel or DPI.

Every Reads are fine loading the document, getting page count, getting the first page num but when it comes to render the page to an image, first Read(p []byte) calls are fine but after a specific read on the document (fairly large []byte, few kb), pdfium triggers a segmentation violation.

I thought it was the go-pdfium go_read_seeker_cb function that was faulty, but when I open the file locally and pass it to OpenDocument as a `ReadSeeker`, it works !

I think it is my `ReadSeeker` implementation that is missing something related to the memory management that I don't understand. Few ideas around the GC detroying the bytes before pdfium has a chance to use it, i don't know...

Do you guys have already experienced this kind of errors ? How do you debug these ?

Thanks a lot !

```
SIGSEGV: segmentation violation
PC=0x7ff9720b78d7 m=4 sigcode=128
signal arrived during cgo execution

goroutine 50 [syscall]:
runtime.cgocall(0xd2bc20, 0xc00001bc18)
	/home/yann/.gvm/gos/go1.21.4/src/runtime/cgocall.go:157 +0x4b fp=0xc00001bbf0 sp=0xc00001bbb8 pc=0x41348b
github.com/klippa-app/go-pdfium/internal/implementation_cgo._Cfunc_FPDF_LoadPage(0x7ff920000d00, 0x0)
	_cgo_gotypes.go:3598 +0x4c fp=0xc00001bc18 sp=0xc00001bbf0 pc=0xca7fac
github.com/klippa-app/go-pdfium/internal/implementation_cgo.(*PdfiumImplementation).loadPage.func1(0x100f820?, {0xc000124918?, 0x0?})
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/internal/implementation_cgo/page.go:48 +0x5c fp=0xc00001bc58 sp=0xc00001bc18 pc=0xce647c
github.com/klippa-app/go-pdfium/internal/implementation_cgo.(*PdfiumImplementation).loadPage(0xc0005c8100, {0xc000124918?, 0x0?})
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/internal/implementation_cgo/page.go:48 +0x245 fp=0xc00001bca0 sp=0xc00001bc58 pc=0xce6345
github.com/klippa-app/go-pdfium/internal/implementation_cgo.(*PdfiumImplementation).getPageSize(0xc00001bd88?, {0xc000124918?, 0x0?})
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/internal/implementation_cgo/render.go:31 +0x1d fp=0xc00001bcd8 sp=0xc00001bca0 pc=0xce6bfd
github.com/klippa-app/go-pdfium/internal/implementation_cgo.(*PdfiumImplementation).calculateRenderImageSize(0x0?, {0xc000124918?, 0x0?}, 0x2e2, 0x420)
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/internal/implementation_cgo/render.go:173 +0x2b fp=0xc00001bd28 sp=0xc00001bcd8 pc=0xce7cab
github.com/klippa-app/go-pdfium/internal/implementation_cgo.(*PdfiumImplementation).RenderPageInPixels(0xc0005c8100, 0xc00022a390)
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/internal/implementation_cgo/render.go:219 +0x13a fp=0xc00001bdf0 sp=0xc00001bd28 pc=0xce7f5a
github.com/klippa-app/go-pdfium/single_threaded.(*pdfiumInstance).RenderPageInPixels(0x150d560?, 0xc00011a020?)
	/home/yann/GO/pkg/mod/github.com/klippa-app/go-pdfium@v1.10.0/single_threaded/generated.go:6129 +0xb4 fp=0xc00001be48 sp=0xc00001bdf0 pc=0xd23454
github.com/org/repo/internal/pdf_test.TestPDFCPUPerf(0xc0000e6680)
	/home/yann/00_Projects/repo/internal/pdf/pdf_public_test.go:248 +0x58e fp=0xc00001bf70 sp=0xc00001be48 pc=0xd2726e
testing.tRunner(0xc0000e6680, 0x11958c8)
	/home/yann/.gvm/gos/go1.21.4/src/testing/testing.go:1595 +0xff fp=0xc00001bfc0 sp=0xc00001bf70 pc=0x5337ff
testing.(*T).Run.func1()
	/home/yann/.gvm/gos/go1.21.4/src/testing/testing.go:1648 +0x25 fp=0xc00001bfe0 sp=0xc00001bfc0 pc=0x534785
runtime.goexit()
	/home/yann/.gvm/gos/go1.21.4/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00001bfe8 sp=0xc00001bfe0 pc=0x47ce41
created by testing.(*T).Run in goroutine 1
	/home/yann/.gvm/gos/go1.21.4/src/testing/testing.go:1648 +0x3ad
```

**Comment by yanc0** [comment]
Hi everyone, a little update on this. I managed to get more precise information on this by opening the program with `gdb`. The segmentation fault apparently appears in the freefont library:

```
Thread 10 "debug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8bfff6c0 (LWP 152388)]
0x00007ffff7d7ae5c in cff_size_init () from /opt/pdfium/lib/libpdfium.so
(gdb) backtrace
#0  0x00007ffff7d7ae5c in cff_size_init () from /opt/pdfium/lib/libpdfium.so
#1  0x00000000010befc5 in FT_New_Size ()
#2  0x00000000010bf1bb in FT_Open_Face ()
#3  0x00000000010bf544 in FT_New_Memory_Face ()
#4  0x00007ffff7cf11d2 in CFX_Face::New(FT_LibraryRec_*, fxcrt::RetainPtr<fxcrt::Retainable>, pdfium::span<unsigned char const>, long) () from /opt/pdfium/lib/libpdfium.so
#5  0x00007ffff7cf9a8f in CFX_FontMgr::NewFixedFace(fxcrt::RetainPtr<CFX_FontMgr::FontDesc>, pdfium::span<unsigned char const>, unsigned long) () from /opt/pdfium/lib/libpdfium.so
#6  0x00007ffff7cf4fa0 in CFX_Font::LoadEmbedded(pdfium::span<unsigned char const>, bool, unsigned long) () from /opt/pdfium/lib/libpdfium.so
#7  0x00007ffff7e29059 in CPDF_Font::LoadFontDescriptor(CPDF_Dictionary const*) () from /opt/pdfium/lib/libpdfium.so
#8  0x00007ffff7e2cc54 in CPDF_SimpleFont::LoadCommon() () from /opt/pdfium/lib/libpdfium.so
#9  0x00007ffff7e29abd in CPDF_Font::Create(CPDF_Document*, fxcrt::RetainPtr<CPDF_Dictionary>, CPDF_Font::FormFactoryIface*) () from /opt/pdfium/lib/libpdfium.so
#10 0x00007ffff7c46b9a in CPDF_DocPageData::GetFont(fxcrt::RetainPtr<CPDF_Dictionary>) () from /opt/pdfium/lib/libpdfium.so
#11 0x00007ffff7c69853 in CPDF_StreamContentParser::FindFont(fxcrt::ByteString const&) () from /opt/pdfium/lib/libpdfium.so
#12 0x00007ffff7c6331e in CPDF_StreamContentParser::Handle_SetFont() () from /opt/pdfium/lib/libpdfium.so
#13 0x00007ffff7c66de7 in CPDF_StreamContentParser::OnOperator(fxcrt::StringViewTemplate<char>) () from /opt/pdfium/lib/libpdfium.so
#14 0x00007ffff7c6a377 in CPDF_StreamContentParser::Parse(pdfium::span<unsigned char const>, unsigned int, unsigned int, std::__Cr::vector<unsigned int, std::__Cr::allocator<unsigned int> > const&) ()
   from /opt/pdfium/lib/libpdfium.so
#15 0x00007ffff7c3f458 in CPDF_ContentParser::Parse() () from /opt/pdfium/lib/libpdfium.so
#16 0x00007ffff7c3eb78 in CPDF_ContentParser::Continue(PauseIndicatorIface*) () from /opt/pdfium/lib/libpdfium.so
#17 0x00007ffff7c59e4c in CPDF_PageObjectHolder::ContinueParse(PauseIndicatorIface*) () from /opt/pdfium/lib/libpdfium.so
#18 0x00007ffff7d6105f in FPDF_LoadPage () from /opt/pdfium/lib/libpdfium.so
#19 0x0000000000f309aa in _cgo_57a9536fc429_Cfunc_FPDF_LoadPage (v=0xc00063f5e0) at /tmp/go-build/cgo-gcc-prolog:462
#20 0x0000000000480068 in runtime.asmcgocall () at /home/yann/.gvm/gos/go1.21.4/src/runtime/asm_amd64.s:872
#21 0x000000000042d00f in runtime.SetFinalizer.func2 () at /home/yann/.gvm/gos/go1.21.4/src/runtime/mfinal.go:484
#22 0x000000000047e46a in runtime.systemstack () at /home/yann/.gvm/gos/go1.21.4/src/runtime/asm_amd64.s:509
#23 0x0100000000000000 in ?? ()
#24 0x0000000000800000 in crypto/tls.(*clientHandshakeState).doFullHandshake (hs=0x0, ~r0=...) at /home/yann/.gvm/gos/go1.21.4/src/crypto/tls/handshake_client.go:659
#25 0x0000000000000000 in ?? ()
```

**Comment by yanc0** [comment]
Nevermind, my ReadSeeker implementation was messy, after a complete refactoring it works fine ! I still don't know what happened initially.

Have a great day !
